grpc:
  port: 8081

logging:
  path: logs
  level: DEBUG
  level.org.hibernate: DEBUG
  level.com.github.windmill312: DEBUG

spring:
  application:
    name: coffee-house
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_coffeehouse
    username: a.sychev
    password: "Ujkjcjdfzgjxnf8"


  jpa:
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false