grpc:
  port: 8081

logging:
  path: logs
  level: DEBUG
  level.org.hibernate: DEBUG
  level.com.sychev: DEBUG

spring:
  application:
    name: coffee-house
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/coffeehouse"
    username: postgres
    password: "Ujkjcjdfzgjxnf8"


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQLDialect